title: Cairn
permalink: pretty
remote_theme: pmarsceill/just-the-docs
site.url: https://es.cairnrpg.com
logo: "/img/logo.png"
color_scheme: light
encoding: UTF-8
plugins:
  - jekyll-redirect-from
include:
  - js

    # Aux links for thttps://laesquinadelrol.com/he upper right navigation
aux_links:
  "Ir a La esquina del rol":
    - "https://laesquinadelrol.com/"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false

heading_anchors: true

# Google Analytics Tracking (optional)

 # e.g, UA-1234567-89

 ga_tracking: G-0TCH74M3EG
 ga_tracking_anonymize_ip: true

 # Use GDPR compliant Google Analytics settings (true by default)
 
# Back to top link

back_to_top: true

back_to_top_text: "Ir arriba"

footer_content: "El texto traducido de esta página está bajo una licencia <a href=\"https://creativecommons.org/licenses/by-sa/4.0\">CC-BY-SA 4.0.</a>"
# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# If you want to ignore the monsters folder during builds
# exclude: /resources/monsters
